disabled_rules:
- trailing_whitespace

opt_in_rules:
- empty_count
- empty_string

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

line_length:
    warning: 100
    error: 150
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
    
function_body_length:
    warning: 200
    error: 400

function_parameter_count:
    warning: 4
    error: 6
    
type_body_length:
    warning: 200
    error: 400
    
file_length:
    warning: 800
    error: 1000
    ignore_comment_only_lines: true
    
cyclomatic_complexity:
    warning: 8
    error: 10

reporter: "xcode"
