#!/bin/bash

# Run branch restriction script
./.git/hooks/pre-commit-branch-restriction.sh
if [[ $? != 0 ]]; then
  exit 1
fi

# Run SwiftLint script
./.git/hooks/pre-commit-swiftlint.sh
if [[ $? != 0 ]]; then
  exit 1
fi

# Run the SPM verification script
./.git/hooks/verify_spm_dependencies.sh
if [[ $? != 0 ]]; then
  exit 1
fi

# Run unit tests script
./.git/hooks/pre-commit-unit-tests.sh
if [[ $? != 0 ]]; then
  exit 1
fi

# Exit with success
exit 0
